version: 2

models:
  - name: d_geographic
    description: "Tabela dimensão geográfica que combina cidades, estados e países"
    columns:
      - name: geo_id
        description: "Chave primária da tabela composta pelas outras chaves"
        tests: 
          - not_null
          - unique
      - name: city_id
        description: "ID único da cidade"
      - name: city
        description: "Nome da cidade"
      - name: state_id
        description: "ID único do estado"
      - name: state_name
        description: "Nome do estado"
      - name: country_id
        description: "ID único do país"
      - name: country
        description: "Nome do país"

  - name: d_calendar
    description: "Tabela dimensão de tempo combinando tempo, semana, dia da semana, mês e ano"
    columns:
      - name: time_id
        description: "ID único do tempo"
        tests:
          - not_null
          - unique
      - name: action_timestamp
        description: "Timestamp da ação"
      - name: week_id
        description: "ID da semana"
      - name: action_week
        description: "Semana de ação"
      - name: weekday_id
        description: "ID do dia da semana"
      - name: action_weekday
        description: "Dia da semana de ação"
      - name: month_id
        description: "ID do mês"
      - name: action_month
        description: "Mês de ação"
      - name: year_id
        description: "ID do ano"
      - name: action_year
        description: "Ano de ação"

  - name: d_customer_accounts
    description: "Tabela combinando informações de clientes e contas"
    columns:
      - name: account_id
        description: "ID único da conta"
        tests: 
          - not_null
          - unique
      - name: customer_id
        description: "ID único do cliente"
        tests:
          - not_null
      - name: first_name
        description: "Primeiro nome do cliente"
      - name: last_name
        description: "Último nome do cliente"
      - name: customer_city
        description: "ID da cidade do cliente"
      - name: cpf
        description: "CPF do cliente"
      - name: country_name
        description: "Nome do país"
      - name: created_at
        description: "Data de criação da conta"
      - name: status
        description: "Status da conta"
      - name: account_branch
        description: "Filial da conta"
      - name: account_check_digit
        description: "Dígito verificador da conta"
      - name: account_number
        description: "Número da conta"

  - name: f_movements
    description: "Tabela fato com as movimentações via transação e via pix, tanto para entradas quanto saídas"
    columns:
      - name: id
        description: "ID Único da movimentação"
        tests: 
          - not_null
          - unique
      - name: account_id
        description: "Chave estrangeira da tabela accounts"
      - name: amount
        description: "Valor da movimentação"
      - name: movement_requested_at
        description: "Timestamp da hora que foi solicitada a movimentação"
      - name: movement_completed_at
        description: "Timestamp da hora que foi completada a movimentação"
      - name: status
        description: "Status da movimentação"
      - name: movement_type
        description: "Tipo de movimentação"
      - name: in_or_out
        description: "Entrada ou saída"

