version: 2

sources:
  - name: raw-data
    database: raw-data-431111
    schema: nubank
    tables:
      - name: accounts
      - name: city
      - name: customers
      - name: d_month
      - name: d_time
      - name: d_week
      - name: d_weekday
      - name: d_year
      - name: pix_moviments
      - name: state
      - name: transfer_ins
      - name: transfer_outs


models:
  - name: stg_accounts
    description: "Tabela dimensão de accounts"
    columns:
      - name: account_id
        description: "ID único da account"
        tests: 
          - not_null
          - unique
      - name: customer_id
        description: "Chave estrangeira da tabela customer"
      - name: created_at
        description: "Data de criação da account"
      - name: status
        description: "Status da account"
      - name: account_branch
        description: "Filial da account"
      - name: account_check_digit
        description: "Digito da account"
      - name: account_number
        description: "Número da account"